import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Home, 
  BookOpen, 
  Flower2, 
  Compass, 
  Heart, 
  Flame, 
  LogOut, 
  Sparkles, 
  CloudRain, 
  Sun 
} from 'lucide-react';
import { RoomId } from './types';

// Import subcomponents
import CustomCursor from './components/CustomCursor';
import MusicPlayer from './components/MusicPlayer';
import CottageLoader from './components/CottageLoader';
import HomeRoom from './components/HomeRoom';
import BedroomRoom from './components/BedroomRoom';
import GardenRoom from './components/GardenRoom';
import VanityRoom from './components/VanityRoom';
import BookshelfRoom from './components/BookshelfRoom';
import MemoryBoxRoom from './components/MemoryBoxRoom';
import LittleCafeRoom from './components/LittleCafeRoom';
import GuestbookRoom from './components/GuestbookRoom';
import MiniGamesRoom from './components/MiniGamesRoom';

// Static assets generated by our image-generation tool
const PINK_COTTAGE_IMAGE = '/src/assets/images/pink_cottage_loading_1782875176425.jpg';
const DREAMY_GIRL_IMAGE = '/src/assets/images/dreamy_cottage_girl_1782875190907.jpg';

interface PetalParticle {
  id: number;
  x: number;
  y: number;
  size: number;
  rotate: number;
  delay: number;
  duration: number;
}

export default function App() {
  const [currentRoom, setCurrentRoom] = useState<RoomId | 'loader' | 'closing'>('loader');
  
  // Music & audio state
  const [isPlayingMusic, setIsPlayingMusic] = useState(false);
  const [hasInteracted, setHasInteracted] = useState(false);

  // Background ambience toggles
  const [weather, setWeather] = useState<'sunshine' | 'rain'>('sunshine');
  const [floatingPetals, setFloatingPetals] = useState<PetalParticle[]>([]);

  // Trigger burst of petals (e.g. from Vanity perfume or Garden flower clicking)
  const triggerPetalShower = () => {
    const burst: PetalParticle[] = Array.from({ length: 15 }).map((_, i) => ({
      id: Date.now() + i,
      x: Math.random() * 100,
      y: -10,
      size: Math.random() * 14 + 6,
      rotate: Math.random() * 360,
      delay: Math.random() * 0.4,
      duration: Math.random() * 3 + 2,
    }));
    setFloatingPetals((prev) => [...prev, ...burst]);
  };

  // Automatically seed persistent floating petals
  useEffect(() => {
    const initialPetals = Array.from({ length: 12 }).map((_, i) => ({
      id: i,
      x: Math.random() * 100,
      y: Math.random() * 100,
      size: Math.random() * 12 + 6,
      rotate: Math.random() * 360,
      delay: 0,
      duration: Math.random() * 10 + 8,
    }));
    setFloatingPetals(initialPetals);
  }, []);

  const handleOpenDoor = () => {
    setHasInteracted(true);
    setIsPlayingMusic(true);
    setCurrentRoom('home');
  };

  const handleExitWorld = () => {
    setCurrentRoom('closing');
  };

  const handleReenterWorld = () => {
    setCurrentRoom('home');
  };

  return (
    <div className="min-h-screen relative overflow-x-hidden flex flex-col justify-between selection:bg-pink-200">
      
      {/* Custom Sparkle Ribbon Cursor */}
      <CustomCursor />

      {/* Persistent floating floral petal elements */}
      <div className="fixed inset-0 pointer-events-none z-[80] overflow-hidden">
        {floatingPetals.map((petal) => (
          <motion.div
            key={petal.id}
            initial={{ y: petal.y - 15, x: `${petal.x}%`, rotate: petal.rotate, opacity: 0 }}
            animate={{ 
              y: window.innerHeight + 50,
              x: `${petal.x + Math.sin(petal.id) * 10}%`,
              rotate: petal.rotate + 360,
              opacity: [0, 0.7, 0.7, 0]
            }}
            transition={{
              duration: petal.duration,
              delay: petal.delay,
              repeat: Infinity,
              ease: 'linear'
            }}
            className="absolute text-pink-300/45 select-none"
            style={{ fontSize: `${petal.size}px` }}
          >
            🌸
          </motion.div>
        ))}
      </div>

      {/* Weather Layer: Rain or Sunbeams */}
      <AnimatePresence>
        {weather === 'rain' && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 0.25 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 pointer-events-none bg-sky-900/10 z-[70]"
          >
            {/* Visual rain streaks */}
            <div className="absolute inset-0 bg-[linear-gradient(170deg,rgba(255,255,255,0)_0%,rgba(255,255,255,0.15)_50%,rgba(255,255,255,0)_100%)] bg-[size:120px_400px] animate-pulse" />
          </motion.div>
        )}
        {weather === 'sunshine' && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 0.15 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 pointer-events-none bg-gradient-to-tr from-amber-200/20 via-transparent to-pink-100/10 z-[70]"
          />
        )}
      </AnimatePresence>

      {/* Floater controls for weather toggling */}
      {currentRoom !== 'loader' && currentRoom !== 'closing' && (
        <div className="fixed top-24 right-6 z-[1000] flex flex-col gap-2">
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={() => setWeather(weather === 'sunshine' ? 'rain' : 'sunshine')}
            className="w-10 h-10 rounded-full glass-panel-pink flex items-center justify-center shadow-md text-[#ff808b] border border-[#ffb3b8]/40 cursor-pointer interactive-obj"
            title={`Switch to ${weather === 'sunshine' ? 'Cozy Rain' : 'Morning Sun'}`}
          >
            {weather === 'sunshine' ? <CloudRain className="w-4 h-4" /> : <Sun className="w-4 h-4" />}
          </motion.button>
        </div>
      )}

      {/* Floating Web Audio procedural music player */}
      <MusicPlayer 
        isPlaying={isPlayingMusic} 
        setIsPlaying={setIsPlayingMusic} 
        hasInteracted={hasInteracted} 
      />

      {/* MAIN SCREEN DISPATCHER */}
      <div className="flex-1 w-full flex flex-col">
        <AnimatePresence mode="wait">
          
          {/* LOADER INTRO SCREEN */}
          {currentRoom === 'loader' && (
            <motion.div
              key="loader"
              exit={{ opacity: 0, scale: 1.02 }}
              transition={{ duration: 1 }}
              className="w-full flex-1"
            >
              <CottageLoader onEnter={handleOpenDoor} pinkCottageImage={PINK_COTTAGE_IMAGE} />
            </motion.div>
          )}

          {/* ACTIVE COTTAGE WORLD LAYOUT */}
          {currentRoom !== 'loader' && currentRoom !== 'closing' && (
            <motion.div
              key="cottage-world"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="w-full flex flex-col justify-between min-h-screen"
            >
              {/* Header Ribbon Scrapbook Navigation */}
              <header className="sticky top-0 z-[90] w-full px-4 py-3 glass-panel-pink border-b border-[#ffb3b8]/30 shadow-sm flex items-center justify-between">
                
                {/* Logo */}
                <button 
                  onClick={() => setCurrentRoom('home')}
                  className="flex items-center gap-1.5 cursor-pointer interactive-obj group"
                >
                  <span className="font-serif text-xl font-bold tracking-widest text-[#5E3A3A] group-hover:text-[#ff808b] transition-colors">mysl.</span>
                  <div className="w-2 h-2 bg-[#ffb3b8] rounded-full animate-ping" />
                </button>

                {/* Ribbon Bow Nav items */}
                <nav className="hidden md:flex items-center gap-1">
                  {[
                    { id: 'home', label: '🏡 Cottage Map' },
                    { id: 'bedroom', label: '🛏️ Bedroom' },
                    { id: 'garden', label: '🌿 Garden' },
                    { id: 'vanity', label: '💄 Vanity' },
                    { id: 'bookshelf', label: '📚 Scrapbook' },
                    { id: 'guestbook', label: '✍️ Guestbook' },
                    { id: 'games', label: '🧸 Play' },
                  ].map((room) => (
                    <button
                      key={room.id}
                      onClick={() => setCurrentRoom(room.id as RoomId)}
                      className={`px-3 py-1.5 rounded-full font-serif text-xs tracking-wider transition-all cursor-pointer border interactive-obj ${
                        currentRoom === room.id
                          ? 'bg-[#ffb3b8] text-white border-white'
                          : 'bg-transparent text-[#5E3A3A] border-transparent hover:bg-[#FFEBEB]/40 hover:border-pink-100'
                      }`}
                    >
                      {room.label}
                    </button>
                  ))}
                </nav>

                {/* Utility: Exit Cottage button */}
                <div className="flex items-center gap-2">
                  {/* Mobile room index trigger */}
                  <div className="md:hidden">
                    <select
                      value={currentRoom}
                      onChange={(e) => setCurrentRoom(e.target.value as RoomId)}
                      className="px-2.5 py-1.5 bg-white border border-[#ffd6d9] rounded-xl text-xs font-serif text-[#5E3A3A] focus:outline-none focus:border-[#ff808b]"
                    >
                      <option value="home">🏡 Cottage Map</option>
                      <option value="bedroom">🛏️ Bedroom</option>
                      <option value="garden">🌿 Garden</option>
                      <option value="vanity">💄 Vanity</option>
                      <option value="bookshelf">📚 Scrapbook</option>
                      <option value="guestbook">✍️ Guestbook</option>
                      <option value="games">🧸 Play Cabinet</option>
                    </select>
                  </div>

                  <button
                    onClick={handleExitWorld}
                    className="px-3.5 py-1.5 bg-[#FFF5F6] hover:bg-[#ffebeb] border border-[#ffb3b8]/40 rounded-full text-[10px] font-serif text-[#ff808b] tracking-wider uppercase transition-all flex items-center gap-1.5 cursor-pointer interactive-obj"
                    title="Leave little world"
                  >
                    <LogOut className="w-3.5 h-3.5" />
                    <span className="hidden sm:inline">Close Cottage Door</span>
                  </button>
                </div>
              </header>

              {/* Main Room Screen Area */}
              <main className="flex-1 w-full py-8">
                <AnimatePresence mode="wait">
                  <motion.div
                    key={currentRoom}
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -12 }}
                    transition={{ duration: 0.5, ease: 'easeOut' }}
                    className="w-full h-full"
                  >
                    {currentRoom === 'home' && (
                      <HomeRoom 
                        onNavigate={(room) => setCurrentRoom(room)} 
                        girlIllustration={DREAMY_GIRL_IMAGE} 
                      />
                    )}
                    {currentRoom === 'bedroom' && (
                      <BedroomRoom onTriggerPetals={triggerPetalShower} />
                    )}
                    {currentRoom === 'garden' && (
                      <GardenRoom onTriggerPetals={triggerPetalShower} />
                    )}
                    {currentRoom === 'vanity' && (
                      <VanityRoom onTriggerPetals={triggerPetalShower} />
                    )}
                    {currentRoom === 'bookshelf' && (
                      <BookshelfRoom />
                    )}
                    {currentRoom === 'memory-box' && (
                      <MemoryBoxRoom />
                    )}
                    {currentRoom === 'little-cafe' && (
                      <LittleCafeRoom />
                    )}
                    {currentRoom === 'guestbook' && (
                      <GuestbookRoom />
                    )}
                    {currentRoom === 'games' && (
                      <MiniGamesRoom />
                    )}
                  </motion.div>
                </AnimatePresence>
              </main>

              {/* Sweet bottom footer */}
              <footer className="w-full py-6 mt-12 border-t border-pink-100/40 text-center flex flex-col items-center gap-1">
                <span className="font-handwritten text-xl text-pink-300">mysl.</span>
                <span className="font-garamond italic text-xs text-[#8A7171] uppercase tracking-wider">
                  made with premium warmth and coquette cozyness • est. 2008
                </span>
              </footer>
            </motion.div>
          )}

          {/* CLOSING DOOR SCREEN */}
          {currentRoom === 'closing' && (
            <motion.div
              key="closing"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 z-[9999] bg-[#FAF6F0] flex flex-col items-center justify-center p-4 overflow-hidden"
            >
              {/* Sunbeams fading */}
              <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-[#FFEEDD] rounded-full blur-[100px] opacity-40 pointer-events-none" />

              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 1 }}
                className="w-full max-w-xl glass-panel-deep rounded-3xl p-6 md:p-8 flex flex-col items-center text-center shadow-2xl relative border border-[#ffb3b8]/30"
              >
                {/* Cottage illustration frame with closing overlay */}
                <div className="relative w-full aspect-[16/10] rounded-2xl overflow-hidden shadow-inner border border-stone-100 mb-8 mt-2">
                  <img
                    src={PINK_COTTAGE_IMAGE}
                    alt="Whimsical Pink Cottage Garden"
                    className="w-full h-full object-cover filter brightness-75 transition-all"
                    referrerPolicy="no-referrer"
                  />
                  {/* Closing shadows */}
                  <div className="absolute inset-0 bg-gradient-to-t from-stone-900/60 via-stone-900/40 to-transparent" />
                </div>

                <div className="flex flex-col gap-2 mb-8">
                  <h1 className="font-serif text-3xl text-[#5E3A3A] tracking-wide">
                    Thank you for visiting <span className="text-[#ff808b]">mysl.</span>
                  </h1>
                  <p className="font-garamond italic text-lg text-[#7A5A5A]">
                    "The cottage door slowly closes..."
                  </p>
                  <p className="font-garamond italic text-lg text-[#7A5A5A] mt-1">
                    See you again in my little world. ✿
                  </p>
                </div>

                {/* Back inside / Enter again button */}
                <button
                  onClick={handleReenterWorld}
                  className="px-8 py-3.5 bg-gradient-to-r from-[#ffd6d9] to-[#ffb3b8] hover:from-[#ffb3b8] hover:to-[#ff808b] text-white rounded-full font-serif tracking-widest text-sm shadow-md hover:shadow-lg transition-all border border-white/40 cursor-pointer flex items-center gap-1.5 interactive-obj"
                >
                  <Sparkles className="w-4 h-4" />
                  Enter Cottage Again
                </button>
              </motion.div>
            </motion.div>
          )}

        </AnimatePresence>
      </div>

    </div>
  );
}
